#!/bin/bash

#
# This Script is used to build NDK, move the NDK executables to res/raw/ndk directory and then run ANT to build the Android 
# Executable file
#
# Execute:  ./build.sh          (this will build the NDK executables.)
# 


#VARIABLES
LINE="================================================="
SCRIPT="[build.sh]"
EP=1
VAR=${1}
SLEEP=1

#COMMANDS
clear

echo "$LINE"
echo "$LINE"
echo "$SCRIPT BUILDING NDK PACKAGE"
echo "$LINE"
echo "$SCRIPT ndk-build"
echo
ndk-build
echo
echo
sleep $SLEEP

echo "$LINE"
echo "$SCRIPT MOVING THE EXECUTABLES"
echo "$LINE"
echo "rm -fr ./assets/*"
rm -fr ./assets/*
echo "$SCRIPT cd ./libs"
cd ./libs
echo "$SCRIPT cp -r ./arm64-v8a ./armeabi ./armeabi-v7a ./mips ./mips64 ./x86 ./x86_64 ../assets"
cp -r ./arm64-v8a ./armeabi ./armeabi-v7a ./mips ./mips64 ./x86 ./x86_64 ../assets
cd ../
echo
echo
sleep $SLEEP

echo "$LINE"
echo "$SCRIPT BUIDLING COMPLETE"
echo "$LINE"
echo "$SCRIPT [INFO] RUN ./install.sh [debug/release] TO INSTALL THE PROJECT ON THE DEVICE"
echo "$LINE$LINE$LINE"
echo "************************************************************************************************************************"
echo
sleep $SLEEP
